USE [master]
GO

/****** Object:  Database [CropDeal]    Script Date: 17-11-2022 17:58:09 ******/
CREATE DATABASE [CropDeal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CropDeal', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\CropDeal.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CropDeal_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\CropDeal_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CropDeal] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CropDeal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CropDeal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CropDeal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CropDeal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CropDeal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CropDeal] SET ARITHABORT OFF 
GO

ALTER DATABASE [CropDeal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CropDeal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CropDeal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CropDeal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CropDeal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CropDeal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CropDeal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CropDeal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CropDeal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CropDeal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CropDeal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CropDeal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CropDeal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CropDeal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CropDeal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CropDeal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CropDeal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CropDeal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CropDeal] SET  MULTI_USER 
GO

ALTER DATABASE [CropDeal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CropDeal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CropDeal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CropDeal] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CropDeal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CropDeal] SET  READ_WRITE 
GO


